/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ExButtonGroup: typeof import('./src/components/ExForm/components/ExButtonGroup/index.vue')['default']
    ExCalendar: typeof import('./src/components/ExCalendar/index.vue')['default']
    ExContextMenu: typeof import('./src/components/ExContextMenu/index.vue')['default']
    ExCreateForm: typeof import('./src/components/ExCreateForm/index.vue')['default']
    ExForm: typeof import('./src/components/ExForm/index.vue')['default']
    ExInput: typeof import('./src/components/ExForm/components/ExInput/index.vue')['default']
    ExMenu: typeof import('./src/components/ExMenu/index.vue')['default']
    ExSelect: typeof import('./src/components/ExForm/components/ExSelect/index.vue')['default']
    ExSubMenu: typeof import('./src/components/ExMenu/components/ExSubMenu.vue')['default']
    ExTable: typeof import('./src/components/ExTable/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
