/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseCtrls: typeof import('./src/components/ExCreateForm/components/BaseCtrls.vue')['default']
    DiyContainer: typeof import('./src/components/ExForm/DiyContainer.vue')['default']
    DiyContainerCfg: typeof import('./src/components/ExCreateForm/components/DiyContainerCfg.vue')['default']
    DiyDatePickerCfg: typeof import('./src/components/ExCreateForm/components/DiyDatePickerCfg.vue')['default']
    DiyInput: typeof import('./src/components/ExForm/DiyInput/index.vue')['default']
    DiyInputCfg: typeof import('./src/components/ExCreateForm/components/DiyInputCfg.vue')['default']
    DiySelect: typeof import('./src/components/ExForm/DiySelect/index.vue')['default']
    DiySelectCfg: typeof import('./src/components/ExCreateForm/components/DiySelectCfg.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ExCalendar: typeof import('./src/components/ExCalendar/index.vue')['default']
    ExContextMenu: typeof import('./src/components/ExContextMenu/index.vue')['default']
    ExCreateForm: typeof import('./src/components/ExCreateForm/index.vue')['default']
    ExDatePicker: typeof import('./src/components/ExDatePicker/index.vue')['default']
    ExDialog: typeof import('./src/components/ExDialog/index.vue')['default']
    ExDrawer: typeof import('./src/components/ExDrawer/index.vue')['default']
    ExForm: typeof import('./src/components/ExForm/index.vue')['default']
    ExInput: typeof import('./src/components/ExInput/index.vue')['default']
    ExMenu: typeof import('./src/components/ExMenu/index.vue')['default']
    ExSubMenu: typeof import('./src/components/ExMenu/components/ExSubMenu.vue')['default']
    ExTable: typeof import('./src/components/ExTable/index.vue')['default']
    FormConfig: typeof import('./src/components/ExCreateForm/components/FormConfig.vue')['default']
    FormContext: typeof import('./src/components/ExContextMenu/components/FormContext.vue')['default']
    FormFooter: typeof import('./src/components/ExCreateForm/components/FormFooter.vue')['default']
    FormMain: typeof import('./src/components/ExCreateForm/components/FormMain.vue')['default']
    FormSideBar: typeof import('./src/components/ExCreateForm/components/FormSideBar.vue')['default']
    FormTopBar: typeof import('./src/components/ExCreateForm/components/FormTopBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
