/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomTheme: typeof import('./src/style/theme/customTheme/index.scss')['default']
    Dark: typeof import('./src/style/variables/dark.scss')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElementTheme: typeof import('./src/style/theme/elementTheme/index.scss')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ExButtonGroup: typeof import('./src/components/ExForm/components/ExButtonGroup/index.vue')['default']
    ExCalendar: typeof import('./src/components/ExCalendar/index.vue')['default']
    ExContextMenu: typeof import('./src/components/ExContextMenu/index.vue')['default']
    ExCreateForm: typeof import('./src/components/ExCreateForm/index.vue')['default']
    ExForm: typeof import('./src/components/ExForm/index.vue')['default']
    ExInput: typeof import('./src/components/ExForm/components/ExInput/index.vue')['default']
    ExMenu: typeof import('./src/components/ExMenu/index.vue')['default']
    ExSelect: typeof import('./src/components/ExForm/components/ExSelect/index.vue')['default']
    ExTable: typeof import('./src/components/ExTable/index.vue')['default']
    FormFooter: typeof import('./src/components/ExCreateForm/FormFooter.vue')['default']
    FormLabel: typeof import('./src/components/ExCreateForm/components/FormLabel.vue')['default']
    FormMain: typeof import('./src/components/ExCreateForm/FormMain.vue')['default']
    FormSideBar: typeof import('./src/components/ExCreateForm/FormSideBar.vue')['default']
    FormTopBar: typeof import('./src/components/ExCreateForm/FormTopBar.vue')['default']
    index: string./src/components/ExCreateForm/components/FormMain.vue
    'Index.d': typeof import('./src/components/ExCreateForm/index.d.ts')['default']
    Light: typeof import('./src/style/variables/light.scss')['default']
    Main: typeof import('./src/style/exCreateForm/form Main.scss')['default']
    MainForm: typeof import('./src/components/ExCreateForm/components/MainForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/ExCreateForm/scss/sideBar.scss')['default']
    UseDraggables: typeof import('./src/hooks/useDraggables.ts')['default']
    Variables: typeof import('./src/style/variables/index.scss')['default']
    'Vite.config.ts.timestamp1755865177574D599b59566066': typeof import('./vite.config.ts.timestamp-1755865177574-d599b59566066.mjs')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
